mytest:poly.hpp mytest.cpp
	g++ -o mytest poly.hpp mytest.cpp

test1:poly.hpp test1.cpp
	g++ -o test1 poly.hpp test1.cpp

test2:poly.hpp test2.cpp
	g++ -o test2 poly.hpp test2.cpp

test3:poly.hpp test3.cpp
	g++ -o test3 poly.hpp test3.cpp
